FitnessArchitecture/Controllers/ExerciseController.cs
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ExerciseController : Controller 
    {
        private readonly IExerciseService exerciseService;
        public ExerciseController(IExerciseService exerciseService)
        {
            this.exerciseService = exerciseService;
        }

        public IActionResult Index() => View();

        public async Task<IActionResult> GetExercise(int ID)
        {
            var exercise = await exerciseService.GetExercise(ID);
            if (exercise.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(exercise.Data);
            }
            ViewBag.Description = exercise.Description;
            ViewBag.StatusCode = ((int)exercise.StatusCode);
            return View("Error");
        }

        public IActionResult GetExercises()
        {
            var exercises = exerciseService.GetExercises();
            if (exercises.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(exercises.Data);
            }
            ViewBag.Description = exercises.Description;
            ViewBag.StatusCode = ((int)exercises.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/ExerciseListController.cs
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ExerciseListController : Controller
    {
        private readonly IExerciseListService exerciseListService;
        public ExerciseListController(IExerciseListService exerciseListService)
        {
            this.exerciseListService = exerciseListService;
        }

        public async Task<IActionResult> GetExercises()
        {
            var exercises = await exerciseListService.GetExercises(User.Identity.Name);
            if (exercises.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(exercises.Data);
            }
            ViewBag.Description = exercises.Description;
            ViewBag.StatusCode = ((int)exercises.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/ExerciseToListController.cs
using FitnessArchitecture.Domain.Models;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ExerciseToListController : Controller
    {
        private readonly IExerciseToListService addedExerciseService;

        public ExerciseToListController(IExerciseToListService addedExerciseService)
        {
            this.addedExerciseService = addedExerciseService;
        }

        public async Task<IActionResult> AddExerciseToList(int ID)
        {
            var addExercise = new ExerciseToList()
            {
                addedAccountEmail = User.Identity.Name,
                exerciseID = ID,
            };
            var exercise = await addedExerciseService.Create(addExercise);
            if (exercise.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("GetExercises", "Exercise");
            }
            ViewBag.Description = exercise.Description;
            ViewBag.StatusCode = ((int)exercise.StatusCode);
            return View("Error");
        }

        public async Task<IActionResult> DeleteExerciseFromList(int ID)
        {
            var exercise = await addedExerciseService.Delete(ID);
            if (exercise.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("GetExercises", "ExerciseList");
            }
            ViewBag.Description = exercise.Description;
            ViewBag.StatusCode = ((int)exercise.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Views/Exercise/GetExercise.cshtml
@model ExerciseViewModel

@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="/css/product-exercise-get.css">


<div class="form-box">
    <label type="text" class="name">@Model.exerciseName</label>
    <div class="content">
        <form asp-controller="Exercise" asp-action="Index" class="input-group">
            <div class="column1">
                <img src="@Model.exerciseImg" alt="">
            </div>
            <div class="column2">
                <div class="data-box">
                    <input disabled type="text" placeholder="@Model.exerciseCalories">
                    <span>Calories</span>
                </div>
                <div class="data-box">
                    <textarea disabled>@Model.exerciseLongDescription</textarea>
                    <span>Description</span>
                </div>
            </div>
            <button type="submit" class="back-btn">Back</button>
        </form>
    </div>
</div>

FitnessArchitecture/Views/Exercise/GetExercises.cshtml
@model List<ExerciseShortViewModel>

@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="/css/product-exercise-list.css">


<section class="model">
    <h1 class="heading"><span>Exercise list</span> </h1>
    <div class="box-container">
        @{
            foreach (ExerciseShortViewModel product in Model)
            {
                <div class="box">
                    <div class="icons">
                        <a asp-controller="ExerciseToList" asp-action="AddExerciseToList" asp-route-id="@product.exerciseID" class="fas fa-plus"></a>
                        <a asp-controller="Exercise" asp-action="GetExercise" asp-route-id="@product.exerciseID" class="fas fa-eye"></a>
                    </div>
                    <div class="image">
                        <img src="@product.exerciseImg" alt="">
                    </div>
                    <div class="content">
                        <h3>@product.exerciseName</h3>
                        <div class="stars">
                            <h5>Calories: @product.exerciseCalories</h5>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</section>

FitnessArchitecture/Views/Exercise/Index.cshtml
<link rel="stylesheet" href="~/css/product-exercise-index.css">
<link rel="stylesheet" href="~/css/index.css">


<div class="content">
    <section class="index">
        <div class="description">
            <h3>Workout</h3>
            <p>
                Physical exercise improves physical fitness, cardiovascular and immune systems, 
                and mental health. They strengthen muscles, increase stamina, improve lung function, 
                reduce stress, and improve self-esteem. 
                Physical exercise is an effective way to maintain health.
            </p>
        </div>
        <div class="options">
            <div class="list-imgs">
                <img src="~/images/exercise-list-1.png" alt="Exercise list image">
                <img src="~/images/exercise-list-2.png" alt="My exercise list image">
            </div>
            <div class="btns">
                <a asp-controller="Exercise" asp-action="GetExercises" class="all-elements-list-btn">Exercise list</a>
                <a asp-controller="ExerciseList" asp-action="GetExercises" class="my-elements-list-btn">My Exercises</a>
            </div>
        </div>
    </section>
</div>  