FitnessArchitecture/Controllers/ProductController.cs
using FitnessArchitecture.Domain.Models;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace FitnessArchitecture.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index() => View();

        public async Task<IActionResult> GetProduct(int ID)
        {
            var product = await productService.GetProduct(ID);
            if (product.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(product.Data);
            }
            ViewBag.Description = product.Description;
            ViewBag.StatusCode = ((int)product.StatusCode);
            return View("Error");
        }
        
        public IActionResult GetProducts()
        {
            var products = productService.GetProducts();
            if (products.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(products.Data);
            }
            ViewBag.Description = products.Description;
            ViewBag.StatusCode = ((int)products.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/ProductListController.cs
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ProductListController : Controller
    {
        private readonly IProductListService productListService;
        public ProductListController(IProductListService productListService)
        {
            this.productListService = productListService;
        }

        public async Task<IActionResult> GetProducts()
        {
            var products = await productListService.GetProducts(User.Identity.Name);
            if (products.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(products.Data);
            }
            ViewBag.Description = products.Description;
            ViewBag.StatusCode = ((int)products.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/ProductToListController.cs
using FitnessArchitecture.Domain.Models;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ProductToListController : Controller 
    {
        private readonly IProductToListService addedProductService;
        public ProductToListController(IProductToListService addedProductService)
        {
            this.addedProductService = addedProductService;
        }

        public async Task<IActionResult> AddProductToList(int ID)
        {
            var addProduct = new ProductToList()
            {
                addedAccountEmail = User.Identity.Name,
                productID = ID,
            };
            var product = await addedProductService.Create(addProduct);
            if (product.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("GetProducts", "Product");
            }
            ViewBag.Description = product.Description;
            ViewBag.StatusCode = ((int)product.StatusCode);
            return View("Error");
        }

        public async Task<IActionResult> DeleteProductFromList(int ID)
        {
            var product = await addedProductService.Delete(ID);
            if (product.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("GetProducts", "ProductList");
            }
            ViewBag.Description = product.Description;
            ViewBag.StatusCode = ((int)product.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Views/ProductList/GetProducts.cshtml
@model List<ProductShortViewModel>

@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="/css/product-exercise-list.css">


<section class="model">
    <h1 class="heading"><span>Product list</span> </h1>
    <div class="box-container">
        @{
            foreach (ProductShortViewModel product in Model)
            {
                <div class="box">
                    <div class="icons">
                        <a asp-controller="ProductToList" asp-action="DeleteProductFromList" asp-route-id="@product.productID" class="fas fa-minus"></a>
                        <a asp-controller="Product" asp-action="GetProduct" asp-route-id="@product.productID" class="fas fa-eye"></a>
                    </div>
                    <div class="image">
                        <img src="@product.productImg" alt="">
                    </div>
                    <div class="content">
                        <h3>@product.productName</h3>
                        <div class="stars">
                            <h5>Calories: @product.productCalories</h5>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</section>