FitnessArchitecture/Controllers/ExerciseController.cs
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class ExerciseController : Controller 
    {
        private readonly IExerciseService exerciseService;
        public ExerciseController(IExerciseService exerciseService)
        {
            this.exerciseService = exerciseService;
        }

        public IActionResult Index() => View();

        public async Task<IActionResult> GetExercise(int ID)
        {
            var exercise = await exerciseService.GetExercise(ID);
            if (exercise.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(exercise.Data);
            }
            ViewBag.Description = exercise.Description;
            ViewBag.StatusCode = ((int)exercise.StatusCode);
            return View("Error");
        }

        public IActionResult GetExercises()
        {
            var exercises = exerciseService.GetExercises();
            if (exercises.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(exercises.Data);
            }
            ViewBag.Description = exercises.Description;
            ViewBag.StatusCode = ((int)exercises.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/ProductController.cs
using FitnessArchitecture.Domain.Models;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace FitnessArchitecture.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index() => View();

        public async Task<IActionResult> GetProduct(int ID)
        {
            var product = await productService.GetProduct(ID);
            if (product.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(product.Data);
            }
            ViewBag.Description = product.Description;
            ViewBag.StatusCode = ((int)product.StatusCode);
            return View("Error");
        }
        
        public IActionResult GetProducts()
        {
            var products = productService.GetProducts();
            if (products.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(products.Data);
            }
            ViewBag.Description = products.Description;
            ViewBag.StatusCode = ((int)products.StatusCode);
            return View("Error");
        }
    }
}

FitnessArchitecture/Controllers/SleepController.cs
using FitnessArchitecture.Domain.ViewModels.Sleep;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
    public class SleepController : Controller
    {
        private readonly ISleepService sleepService;
        public SleepController(ISleepService sleepService)
        {
            this.sleepService = sleepService;
        }

        public IActionResult Index() => RedirectToAction("GetSleep");

        public async Task<IActionResult> GetSleep()
        {
            var sleep = await sleepService.GetSleep(User.Identity.Name);
            if (sleep.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return View(sleep.Data);
            }
			ViewBag.Description = sleep.Description;
			ViewBag.StatusCode = ((int)sleep.StatusCode);
			return View("~/Views/Home/Error.cshtml");
		}

        public async Task<IActionResult> UpdateSleep(SleepViewModel updateSleep)
        {
            if (ModelState.IsValid)
            {
                var s = new SleepViewModel()
                {
                    sleepAccountEmail = User.Identity.Name,
                    sleepTime = updateSleep.sleepTime,
                };
                var sleep = await sleepService.Update(s);
                if (sleep.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    return RedirectToAction("Index");
                }
				ViewBag.Description = sleep.Description;
				ViewBag.StatusCode = ((int)sleep.StatusCode);
				return View("~/Views/Home/Error.cshtml");
			}
			return View("GetSleep", updateSleep);
		}
	}
}

FitnessArchitecture/Controllers/UserController.cs
using FitnessArchitecture.Domain.ViewModels.User;
using FitnessArchitecture.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FitnessArchitecture.Controllers
{
	public class UserController : Controller
	{
		private readonly IUserService userService;

		public UserController(IUserService userService)
		{
			this.userService = userService;
		}

		[HttpGet]
		public IActionResult RegisterUser() =>	View();

		[HttpPost]
		public async Task<IActionResult> RegisterUser(UserViewModel userInfo)
		{
            if (ModelState.IsValid)
			{
                userInfo.userID = (await userService.GetUser(User.Identity.Name)).Data.userID;
                var user = await userService.UpdateUser(userInfo);

                if (user.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    return RedirectToAction("Index", "Home");
                }
				ViewBag.Description = user.Description;
				ViewBag.StatusCode = ((int)user.StatusCode);
				return View("~/Views/Home/Error.cshtml");
			}
			return View(userInfo);
        }

		[HttpGet]
		public IActionResult UpdateUser() => View();

		[HttpPost]
		public async Task<IActionResult> UpdateUser(UserViewModel userInfo)
		{
			if (ModelState.IsValid)
			{
				userInfo.userID = (await userService.GetUser(User.Identity.Name)).Data.userID;
				var user = await userService.UpdateUser(userInfo);

				if (user.StatusCode == System.Net.HttpStatusCode.OK)
				{
					return RedirectToAction("GetUser");
				}
				ViewBag.Description = user.Description;
				ViewBag.StatusCode = ((int)user.StatusCode);
				return View("~/Views/Home/Error.cshtml");
			}
			return View(userInfo);
		}

		public async Task<IActionResult> GetUser()
		{
			var user = await userService.GetUser(User.Identity.Name);

			if (user.StatusCode == System.Net.HttpStatusCode.OK)
			{
				return View(user.Data);
			}
			ViewBag.Description = user.Description;
			ViewBag.StatusCode = ((int)user.StatusCode);
			return View("~/Views/Home/Error.cshtml");
		}
    }
}

FitnessArchitecture/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fitness</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="~/css/mock.css">

</head>


<body>
    <header class="header">
        <section class="flex">
            <div class="logo">
                <a asp-area="" asp-controller="Home" asp-action="Index">FITNESS</a>
            </div>
            <nav class="navbar">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="Sleep" asp-action="Index">Sleep</a>
                <a asp-area="" asp-controller="Product" asp-action="Index">Nutrition</a>
                <a asp-area="" asp-controller="Exercise" asp-action="Index">Workout</a>
            </nav>
            <div class="icons">
                <a asp-controller="User" asp-action="GetUser" class="fas fa-user" style="color:#fff; cursor: pointer; font-size: 2.5rem;
                    margin-left: 2rem;" onmouseover="this.style.color='#00fceb';" onmouseout="this.style.color='#fff';"></a>
                <a asp-controller="Account" asp-action="LogOut" class="fas fa-sign-out-alt" style="color:#fff; cursor: pointer; font-size: 2.5rem;
                    margin-left: 2rem;" onmouseover="this.style.color='#00fceb';" onmouseout="this.style.color='#fff';"></a>
            </div>
            
        </section>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <section class="footer-section">
            <div class="share">
                <a href="#" class="fab fa-facebook-f"></a>
                <a href="#" class="fab fa-twitter"></a>
                <a href="#" class="fab fa-instagram"></a>
                <a href="#" class="fab fa-linkedin"></a>
                <a href="#" class="fab fa-telegram"></a>
            </div>
            <div class="links">
                <a asp-controller="Home" asp-action="Index">Home</a>
                <a href="#">About</a>
                <a href="#">Privacy</a>
                <a href="#">Support</a>
                <a href="#">Contacts</a>
            </div>    
        </section>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FitnessArchitecture/Views/Shared/_LoginWindow.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="~/css/account-main.css" />
	<title>Fitness</title>
</head>

<body>
	<div class="hero">
		<div class="form-box">
			<div class="button-box">
				<div id="btn"></div>
				<a asp-controller="Account" asp-action="Login" type="button" class="toggle-btn1">Entrance</a>
				<a asp-controller="Account" asp-action="Register" type="button" class="toggle-btn2">Register</a>
			</div>
			@RenderBody()
		</div>
	</div>
</body>
</html>